### ISSUE TITLE
Transaction simulation failed: Error processing Instruction 0: custom program error: 0xf

### ISSUE THREAD

**Issue by g1tt0** [blockworks-foundation/mango-explorer#12]
Hi! I often get an error, I can't find what exactly the problem is. Can you help?

```
Traceback (most recent call last):
  File "/home/*/*/*/*.py", line 76, in cancel_order
    return market_operations.cancel_order(order)
  File "/home/*/mango/lib/python3.9/site-packages/mango/perpmarketoperations.py", line 57, in cancel_order
    return (signers + cancel + crank + settle).execute(self.context)
  File "/home/*/mango/lib/python3.9/site-packages/mango/combinableinstructions.py", line 142, in execute
    raise exception
  File "/home/*/mango/lib/python3.9/site-packages/mango/combinableinstructions.py", line 134, in execute
    response = context.client.send_transaction(transaction, *self.signers)
  File "/home/*/mango/lib/python3.9/site-packages/mango/client.py", line 613, in send_transaction
    response = self.compatible_client.send_transaction(
  File "/home/*/mango/lib/python3.9/site-packages/mango/client.py", line 390, in send_transaction
    response = self._send_request(
  File "/home/*/mango/lib/python3.9/site-packages/mango/client.py", line 451, in _send_request    
raise TransactionException(transaction, exception_message, error_code, self.name, self.cluster_url,
mango.client.TransactionException: « 𝚃𝚛𝚊𝚗𝚜𝚊𝚌𝚝𝚒𝚘𝚗𝙴𝚡𝚌𝚎𝚙𝚝𝚒𝚘𝚗 in 'Mango Explorer' [sendTransaction]: -32002:: Transaction failed with: 'Transaction simulation failed: Error processing Instruction 0: custom program error: 0xf'
    Accounts:
        No Accounts
    Errors:
        {'InstructionError': [0, {'Custom': 15}]}
    Logs:
        Program ********************************invoke [1]
        Program log: Mango: CancelPerpOrderByClientId client_order_id=1111111111111
        Program log: MangoErrorCode::ClientIdNotFound; src/processor.rs:2039
        Program ********************************consumed 4966 of 200000 compute units
        Program ******************************** failed: custom program error: 0xf
```

**Comment by OpinionatedGeek** [comment]
The initial problem is given by the `MangoErrorCode::ClientIdNotFound` line - it looks like you're calling `cancel_order()` with a client ID that isn't on the order book.

This can happen for a few reasons:
* The order has been filled or cancelled already
* The client ID being sent is incorrect

There's some logic in the code to set the client ID to a timestamp (to make some transaction logging better) and it's possible this is interfering with what you're doing. Or it's possible there's something else going on.

If the problem is purely because the order has already been filled or cancelled, you can tell `cancel_order()` to ignore problems if the order doesn't exist. That's probably not what you want if the problem is a mismatch of IDs though.

Can you please provide a simple (devnet) example that reproduces the problem? If you can, that makes it much easier to fix.

Many thanks.

**Comment by g1tt0** [comment]
**simplemarketmaking_testing.py**
```
class SimpleMarketMaker:
    def __init__(self, context: mango.Context, wallet: mango.Wallet, market: mango.LoadedMarket, market_operations: mango.MarketOperations, oracle: mango.Oracle, spread_ratio: Decimal, position_size_ratio: Decimal, existing_order_tolerance: Decimal, pause: timedelta) -> None:
        self.logger: logging.Logger = logging.getLogger(self.__class__.__name__)
        self.context: mango.Context = context
        self.wallet: mango.Wallet = wallet
        self.market: mango.LoadedMarket = market
        self.market_operations: mango.MarketOperations = market_operations
        self.oracle: mango.Oracle = oracle
        self.spread_ratio: Decimal = spread_ratio
        self.position_size_ratio: Decimal = position_size_ratio
        self.existing_order_tolerance: Decimal = existing_order_tolerance
        self.pause: timedelta = pause
        self.stop_requested = False

    def start(self) -> None:
        # On startup there should be no existing orders. If we didn't exit cleanly last time though,
        # there may still be some hanging around. Cancel any existing orders so we start fresh.
        self.cleanup()

        while not self.stop_requested:
            self.logger.info("Starting fresh iteration.")

            try:
                # Calculate what we want the orders to be.
                bid, ask = (Decimal(3000), Decimal(5000))
                buy_quantity, sell_quantity = (Decimal(0.1), Decimal(0.1))

                buy_order: mango.Order = mango.Order.from_basic_info(
                    mango.Side.BUY, bid, buy_quantity, mango.OrderType.POST_ONLY)
                self.market_operations.place_order(buy_order)

                sell_order: mango.Order = mango.Order.from_basic_info(
                    mango.Side.SELL, ask, sell_quantity, mango.OrderType.POST_ONLY)
                self.market_operations.place_order(sell_order)
                time.sleep(5)

                current_orders = self.market_operations.load_my_orders()
                buy_orders = [order for order in current_orders if order.side == mango.Side.BUY]
                for order in buy_orders:
                    self.market_operations.cancel_order(order)
                sell_orders = [order for order in current_orders if order.side == mango.Side.SELL]
                for order in sell_orders:
                    self.market_operations.cancel_order(order)
            except Exception as exception:
                self.logger.warning(
                    f"Pausing and continuing after problem running market-making iteration: {exception} - {traceback.format_exc()}")

    def cleanup(self) -> None:
        self.logger.info("Cleaning up.")
        orders = self.market_operations.load_my_orders()
        for order in orders:
            self.market_operations.cancel_order(order)
```
**main.py**
```
import mango
from simplemarketmaking_testing import SimpleMarketMaker
from decimal import Decimal
from datetime import timedelta


context = mango.ContextBuilder.build(cluster_name="mainnet")
wallet = mango.Wallet.load('wallet.json')
group = mango.Group.load(context)

accounts = mango.Account.load_all_for_owner(context, wallet.address, group)
account = accounts[0]

stub = context.market_lookup.find_by_symbol("ETH-PERP")
market = mango.ensure_market_loaded(context, stub)
market_operations = mango.create_market_operations(context, wallet, account, market, dry_run=False)

oracle_provider = mango.create_oracle_provider(context, "pyth")
oracle = oracle_provider.oracle_for_market(context, market)

mm = SimpleMarketMaker(context=context, wallet=wallet, market=market, market_operations=market_operations,
                       oracle=oracle, spread_ratio=Decimal(1), position_size_ratio=Decimal(1),
                       existing_order_tolerance=Decimal(1), pause=timedelta(days=1))

if __name__ == "__main__":
    mm.start()
```
I thought that the problem was in my code, so I took the code from the example from the repository and simplified it so that orders were simply placed and canceled. Anyway this error appears sometimes.

And I ran into one more error when placing an order:
```
Program log: Mango: PlacePerpOrder client_order_id=****************
Program log: MangoErrorCode::InvalidPriceCache Cache the oracle price to resolve; src/state.rs:588
```

**Comment by OpinionatedGeek** [comment]
Finally getting back to this - apologies for the delay.

The newer `CancelAllPerpOrders` should solve the problem for you. There can be a race condition between what orders you know have been placed, what orders remain on the orderbook, and what orders have been filled. Using `CancelAllPerpOrders` prevents problems where the data fetched has been made out-of-date by an on-chain event in the tiny time window between fetching and executing.

`InvalidPriceCache` is often an indication of heavy TPS on Solana (so the keeper transactions aren't making it through), or the RPC server you're connecting through having some stale data. It may be worth turning `--skip-preflight` on if you haven't already.
