### ISSUE TITLE
Error when trying to run docker container

### ISSUE THREAD

**Issue by gregkonush** [blockworks-foundation/mango-explorer#14]
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-notebook", line 6, in <module>
    from notebook.notebookapp import main
  File "/opt/conda/lib/python3.9/site-packages/notebook/notebookapp.py", line 80, in <module>
    from .services.contents.manager import ContentsManager
  File "/opt/conda/lib/python3.9/site-packages/notebook/services/contents/manager.py", line 17, in <module>
    from nbformat import sign, validate as validate_nb, ValidationError
  File "/opt/conda/lib/python3.9/site-packages/nbformat/__init__.py", line 32, in <module>
    from .validator import validate, ValidationError
  File "/opt/conda/lib/python3.9/site-packages/nbformat/validator.py", line 12, in <module>
    from .json_compat import get_current_validator, ValidationError
  File "/opt/conda/lib/python3.9/site-packages/nbformat/json_compat.py", line 10, in <module>
    import jsonschema
  File "/opt/conda/lib/python3.9/site-packages/jsonschema/__init__.py", line 11, in <module>
    from jsonschema.exceptions import (
  File "/opt/conda/lib/python3.9/site-packages/jsonschema/exceptions.py", line 9, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'

**Comment by OpinionatedGeek** [comment]
Hi. Thanks for reporting this.

I'm afraid I'm a bit baffled. I've never seen this error before, and the current version doesn't include Jupyter or any notebooks.

Can you please give me the steps to reproduce this error? In particular, the command you run to start the docker container and the notebook that is giving the error could really help me track down the source of the problem.

**Comment by i-like-mangos** [comment]
Hi,

I got the same issue. All I did was: 

docker pull opinionatedgeek/mango-explorer

docker run opinionatedgeek/mango-explorer

**Comment by OpinionatedGeek** [comment]
Thanks. I'm still not sure what command you're running to start the container - is it exactly as: `docker run opinionatedgeek/mango-explorer` with no command?

I'm also unsure what you're actually trying to do when you run the container. Most of the useful stuff is in Mango V3, which uses the container `opinionatedgeek/mango-explorer-v3`. The `opinionatedgeek/mango-explorer` is mostly just for running a Mango V2 liquidator but it would require more parameters.

**Comment by BEEMO323** [comment]
Hello,

I am receiving the same error above. Would the documentation for setting up a liquidator within a container from the mango docs & the attached link for the code no longer be in use?

**Comment by OpinionatedGeek** [comment]
Again, I can't really help if you don't tell me the command you're trying to run, and the container image you're using.

The code for the V2 liquidator is in the v2 branch of this repository. It's not out of date, but V2 of Mango is not the current version of Mango.

**Comment by BEEMO323** [comment]
So I am following this doc. https://gitlab.com/OpinionatedGeek/mango-explorer/-/blob/v3/Quickstart.md

When I get to 4. 📜 'mango-explorer' Alias

I run ```
alias mango-explorer="docker run --rm -it --name=mango-explorer \
    -v /var/mango-explorer/id.json:/home/jovyan/work/id.json \
    opinionatedgeek/mango-explorer:latest"
```

More Specifically,

docker run --rm -it --name=mango-explorer \
    -v /var/mango-explorer/id.json:/home/jovyan/work/id.json \
    opinionatedgeek/mango-explorer:latest

& receive 

Traceback (most recent call last):
File "/opt/conda/bin/jupyter-notebook", line 6, in
from notebook.notebookapp import main
File "/opt/conda/lib/python3.9/site-packages/notebook/notebookapp.py", line 80, in
from .services.contents.manager import ContentsManager
File "/opt/conda/lib/python3.9/site-packages/notebook/services/contents/manager.py", line 17, in
from nbformat import sign, validate as validate_nb, ValidationError
File "/opt/conda/lib/python3.9/site-packages/nbformat/init.py", line 32, in
from .validator import validate, ValidationError
File "/opt/conda/lib/python3.9/site-packages/nbformat/validator.py", line 12, in
from .json_compat import get_current_validator, ValidationError
File "/opt/conda/lib/python3.9/site-packages/nbformat/json_compat.py", line 10, in
import jsonschema
File "/opt/conda/lib/python3.9/site-packages/jsonschema/init.py", line 11, in
from jsonschema.exceptions import (
File "/opt/conda/lib/python3.9/site-packages/jsonschema/exceptions.py", line 9, in
import attr
ModuleNotFoundError: No module named 'attr'

If you are saying to use opinionatedgeek/mango-explorer-v3

that is not what is listed.

**Comment by OpinionatedGeek** [comment]
No, if you're following that quickstart you should be using the code in the V2 branch and the container `opinionatedgeek/mango-explorer:latest`. (This is what you are using, which is correct.).

However, just running:
```
docker run --rm -it --name=mango-explorer \
    -v /var/mango-explorer/id.json:/home/jovyan/work/id.json \
    opinionatedgeek/mango-explorer:latest
```
won't work. It expects a command name after that prologue, so please try:
```
mango-explorer show-group
```
(if you've set up the `mango-explorer` alias) or
```
docker run --rm -it --name=mango-explorer \
    -v /var/mango-explorer/id.json:/home/jovyan/work/id.json \
    opinionatedgeek/mango-explorer:latest show-group
```
