### ISSUE TITLE
Group-balance-wallet fails due to "Invalid Public Key Input" exception

### ISSUE THREAD

**Issue by nadavhart** [blockworks-foundation/mango-explorer#19]
Hey there,

Trying to run `group-balance-wallet` from command line, with the dry-run flag everything looks good, but when I run it without it I see the following  exception:

```2021-12-14 08:18:01 ⓘ RetryWithPau Retriable call failed [Place Serum Order And Settle] with error '('invalid public key input:', '<bound method Account.public_key 
of <solana.account.Account object at 0x7f38e3593d30>>')'.
2021-12-14 08:18:01 ⓘ RetryWithPau Will retry [Place Serum Order And Settle] call in 4 second(s).
2021-12-14 08:18:05 ⓘ RetryWithPau Retriable call failed [Place Serum Order And Settle] with error '('invalid public key input:', '<bound method Account.public_key 
of <solana.account.Account object at 0x7f38e3593d30>>')'.
2021-12-14 08:18:05 ⓘ RetryWithPau Will retry [Place Serum Order And Settle] call in 8 second(s).
2021-12-14 08:18:14 ⓘ RetryWithPau Retriable call failed [Place Serum Order And Settle] with error '('invalid public key input:', '<bound method Account.public_key 
of <solana.account.Account object at 0x7f38e3593d30>>')'.
2021-12-14 08:18:14 ⓘ RetryWithPau Will retry [Place Serum Order And Settle] call in 16 second(s).
2021-12-14 08:18:30 ⓘ RetryWithPau Retriable call failed [Place Serum Order And Settle] with error '('invalid public key input:', '<bound method Account.public_key 
of <solana.account.Account object at 0x7f38e3593d30>>')'.
2021-12-14 08:18:30 ⓘ RetryWithPau Will retry [Place Serum Order And Settle] call in 20 second(s).
2021-12-14 08:18:50 ⓘ RetryWithPau Retriable call failed [Place Serum Order And Settle] with error '('invalid public key input:', '<bound method Account.public_key 
of <solana.account.Account object at 0x7f38e3593d30>>')'.
2021-12-14 08:18:50 ⓘ RetryWithPau Will retry [Place Serum Order And Settle] call in 30 second(s).
2021-12-14 08:19:20 ⓘ RetryWithPau End of retry loop for [Place Serum Order And Settle] - propagating exception.
2021-12-14 08:19:20 🛑 root         Balancing stopped because of exception: ('invalid public key input:', '<bound method Account.public_key of <solana.account.Accou
nt object at 0x7f38e3593d30>>') - Traceback (most recent call last):
  File "/home/jovyan/.local/lib/pyston3.8/site-packages/solana/publickey.py", line 31, in __init__
    self._key = base58.b58decode(value)
  File "/home/jovyan/.local/lib/pyston3.8/site-packages/base58/__init__.py", line 124, in b58decode
    acc = b58decode_int(v, alphabet=alphabet, autofix=autofix)
  File "/home/jovyan/.local/lib/pyston3.8/site-packages/base58/__init__.py", line 104, in b58decode_int
    raise ValueError(
ValueError: Invalid character '<'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/jovyan/work/bin/group-balance-wallet", line 61, in <module>
    wallet_balancer.balance(prices)
  File "/home/jovyan/work/mango/walletbalancer.py", line 319, in balance
    self._make_changes(sorted_changes)
  File "/home/jovyan/work/mango/walletbalancer.py", line 331, in _make_changes
    self.trade_executor.buy(market_symbol, change.value.copy_abs())
  File "/home/jovyan/work/mango/tradeexecutor.py", line 191, in buy
    return self._execute(
  File "/home/jovyan/work/mango/tradeexecutor.py", line 280, in _execute
    return retrier.run(transaction, *signers)
  File "/home/jovyan/work/mango/retrier.py", line 84, in run
    raise captured_exception
  File "/home/jovyan/work/mango/retrier.py", line 55, in run
```

Earlier when running AccountScout all looks well and pub key was parsed successfully. What am I doing wrong?

**Comment by OpinionatedGeek** [comment]
Hi,

I don't think you're doing anything wrong, but I can't reproduce this issue. Sorry.

This is using the V2 liquidator code - yes? Are you sure you're using the latest code?

I can explain a bit of background to this specific problem, in case it helps. The Solana Python code used to have an `Account` type to hold the secret key and perform signing. That's deprecated now, and a `Keypair` type is nearly a drop-in replacement.

Unfortunately, it's only _nearly_ a drop-in replacement, and one of the differences is that `Account`'s `public_key()` method became `Keypair`'s `public_key` property. The crux of the error your seeing is some code that is expecting a `Keypair` is trying to read its `public_key` property, but is instead getting a reference to an `Account`'s `public_key()` method. Things go off the rails at that point.

If you're running the project code directly, I'd recommend verifying your dependencies.

**Comment by OpinionatedGeek** [comment]
Hi,

Thanks for that. It turns out it was a dependency issue, but only in the docker container.

I've updated the dependencies, and updated a line of code to reflect the change in the dependency, and it should all work for you now if you pull the latest container.

**Comment by nadavhart** [comment]
Thank you! Works now.
Haven't liquidated anything yet but one can be optimistic ;)
(Closing the issue)
