### ISSUE TITLE
PERP-BTC missing from devnet

### ISSUE THREAD

**Issue by stevel408** [blockworks-foundation/mango-explorer#68]
Hi, I was going though the [marketing making tutorial](https://github.com/blockworks-foundation/mango-explorer/blob/main/docs/MarketmakingQuickstart.md), and encountered an error at the last step (step 11):

```
$ mango-explorer marketmaker --name "BTC-PERP Marketmaker" --market BTC-PERP --oracle-provider pyth --confidenceinterval-position-size-ratio 0.1 --minimumcharge-ratio 0 --confidenceinterval-level 2 --confidenceinterval-level 4 --existing-order-tolerance 0.0001 --pulse-interval 30 --order-type POST_ONLY --biasquoteonposition-bias 0.00003 --log-level DEBUG --cluster-name devnet --dry-run

... ...

2022-08-29 23:21:44 🐛 Reconnecting Closing WebSocket for wss://mango.devnet.rpcpool.com
Traceback (most recent call last):
  File "/app/bin/marketmaker", line 221, in <module>
    market = mango.market(context, args.market)
  File "/app/mango/porcelain.py", line 93, in market
    raise Exception(f"Could not find market {symbol}")
Exception: Could not find market BTC-PERP
```

Upon further examination, I realized that the reason is that PERP-BTC doesn't existing in devnet, but exists in mainnet and testnet, see below:

```
$ poetry run bin/show-market --name mm --cluster-name testnet --market BTC-PERP
... ...

« PerpMarket BTC-PERP 6GTMXmpBdUDAojfjocxxn2nD7C5CiN9i4RLqcC3BWEG7 [BXhdkETgbHrr5QmVBT1xbz3JrMM28u5djbVtmTUfmFTH]
    « PerpMarketDetails Version.V1 [6GTMXmpBdUDAojfjocxxn2nD7C5CiN9i4RLqcC3BWEG7]
        
... ...

$ poetry run bin/show-market --name mm --cluster-name devnet --market BTC-PERP
... ...
Traceback (most recent call last):
  File "/home/stevel/workspace/crypto/solana/mango-explorer/bin/show-market", line 19, in <module>
    market = mango.market(context, args.market)
  File "/home/stevel/workspace/crypto/solana/mango-explorer/mango/porcelain.py", line 93, in market
    raise Exception(f"Could not find market {symbol}")
Exception: Could not find market BTC-PERP
```

If PERP-BTC is indeed missing in devnet, perhaps one of the following two changes should be made?

1. Replace devnet with testnet in the tutorial, or
2. Replace PERP-BTC with something else in the tutorial.

If you guys decide to go one way or another, am happy to submit a PR to save you guys some work...

**Comment by stevel408** [comment]
PR submitted: https://github.com/blockworks-foundation/mango-explorer/pull/69

**Comment by riordanp** [comment]
Fixed in #69
